services:
  meilisearch:
    image: getmeili/meilisearch:v1.1
    container_name: meilisearch
    ports:
      - 7700:7700
    environment:
      MEILI_ENV: development
    volumes:
      - ./docker/meilisearch/data:/meili_data
    restart: always
