services:
  meilisearch:
    image: getmeili/meilisearch:v1.1
    container_name: meilisearch
    ports:
      - ${MS_PORT}:${MS_PORT}
    environment:
      MEILI_ENV: development
      MEILI_HTTP_ADDR: 0.0.0.0:${MS_PORT}
    volumes:
      - ./data:/meili_data
    restart: always
