services:
  engine:
    image: getmeili/meilisearch:v1.1
    container_name: engine
    ports:
      - ${PORT}:${PORT}
    environment:
      MEILI_ENV: development
      MEILI_HTTP_ADDR: 0.0.0.0:${PORT}
    volumes:
      - ./data:/meili_data
    restart: always
    networks:
      - osakana_network

networks:
  osakana_network:
    external: true
