[tool.poetry]
name = "osakana"
version = "0.1.0"
description = "「あとで読む」記事を管理できるWebアプリ"
authors = ["Kazuki Tobita <kazukiti201@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
